[package]
name = "rust_file"
version = "0.1.0"
authors = ["alec <aag3@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filetime = "0.2"
chrono = "0.4"
